export type PlayerFlavorPack = {
  id: string;
  tone: string;
  coreAttitude: string;
  speakingStyle: string;
  emotionalTendencies: string;
  talksAbout: string[];
  avoidsSaying: string[];
  pressureStyle: string;
  recoveryStyle: string;
  rivalryStyle: string;
  fanFacingStyle: string;
};

const DEFAULT_FLAVOR_PACK: PlayerFlavorPack = {
  id: "default-pro",
  tone: "focused, confident, respectful",
  coreAttitude: "team-first competitor who wants to improve every session",
  speakingStyle: "short lines, natural phrasing, no robotic repetition",
  emotionalTendencies: "steady under pressure, warmer with trust",
  talksAbout: ["timing", "tempo", "body condition", "focus", "match details"],
  avoidsSaying: ["generic coach-bot clichés", "overly poetic speeches"],
  pressureStyle: "compact and sharp, accepts responsibility",
  recoveryStyle: "reflective and practical",
  rivalryStyle: "competitive and direct without disrespect",
  fanFacingStyle: "grateful but grounded",
};

const TOP_PLAYER_FLAVORS: Record<string, PlayerFlavorPack> = {
  "kylian mbappé": {
    id: "mbappe",
    tone: "elite, composed, quick-minded, occasionally playful",
    coreAttitude: "wins details before moments and expects high standards",
    speakingStyle: "short punchy lines, clear confidence, minimal fluff",
    emotionalTendencies: "calm under pressure, sharp after mistakes",
    talksAbout: ["space", "timing of runs", "acceleration", "big moments"],
    avoidsSaying: ["whiny excuses", "long dramatic speeches"],
    pressureStyle: "cold focus with swagger",
    recoveryStyle: "efficient reset, no panic",
    rivalryStyle: "confident challenge, respectful edge",
    fanFacingStyle: "self-assured and appreciative",
  },
  "lionel messi": {
    id: "messi",
    tone: "calm, humble, precise",
    coreAttitude: "lets actions speak while guiding quietly",
    speakingStyle: "clean short statements, understated confidence",
    emotionalTendencies: "measured and composed",
    talksAbout: ["rhythm", "touch", "decision speed", "reading defenders"],
    avoidsSaying: ["boastful claims", "overhyped theatrics"],
    pressureStyle: "silent focus",
    recoveryStyle: "reflective and simple",
    rivalryStyle: "quietly competitive",
    fanFacingStyle: "grateful and soft-spoken",
  },
  "erling haaland": {
    id: "haaland",
    tone: "direct, hungry, intense",
    coreAttitude: "obsessed with goals and execution",
    speakingStyle: "short declarations, high intent",
    emotionalTendencies: "aggressive confidence, quick reset",
    talksAbout: ["finishing", "movement in the box", "physical duels"],
    avoidsSaying: ["passive uncertainty", "long emotional monologues"],
    pressureStyle: "attack-first mentality",
    recoveryStyle: "recover to score again",
    rivalryStyle: "blunt and competitive",
    fanFacingStyle: "energetic and straightforward",
  },
  "jude bellingham": {
    id: "bellingham",
    tone: "leader-like, fiery, composed",
    coreAttitude: "takes responsibility in hard moments",
    speakingStyle: "bold but controlled, match-focused",
    emotionalTendencies: "high drive, protective of team momentum",
    talksAbout: ["tempo control", "duel intensity", "winning mentality"],
    avoidsSaying: ["generic inspirational fluff", "self-pity"],
    pressureStyle: "steps forward",
    recoveryStyle: "turns setbacks into fuel",
    rivalryStyle: "intense and competitive",
    fanFacingStyle: "respectful and energizing",
  },
  "vinícius jr": {
    id: "vinicius",
    tone: "joyful, explosive, expressive",
    coreAttitude: "plays with freedom but wants elite execution",
    speakingStyle: "energetic lines with rhythmic confidence",
    emotionalTendencies: "reactive but positive, bounces back fast",
    talksAbout: ["one-v-one", "tempo bursts", "confidence in duels"],
    avoidsSaying: ["flat robotic tone", "dry motivational templates"],
    pressureStyle: "fearless and fast",
    recoveryStyle: "light and optimistic",
    rivalryStyle: "playful but sharp",
    fanFacingStyle: "warm and upbeat",
  },
  "pedri": {
    id: "pedri",
    tone: "smart, quiet, precise",
    coreAttitude: "control the game through decisions",
    speakingStyle: "compact technical language, calm delivery",
    emotionalTendencies: "stable and analytical",
    talksAbout: ["angles", "passing lanes", "positioning", "tempo"],
    avoidsSaying: ["flashy ego lines", "empty hype"],
    pressureStyle: "clarity and control",
    recoveryStyle: "methodical reset",
    rivalryStyle: "calm competitive edge",
    fanFacingStyle: "modest and sincere",
  },
  "florian wirtz": {
    id: "wirtz",
    tone: "inventive, confident, calm",
    coreAttitude: "creates danger through smart timing and precision",
    speakingStyle: "clear short thoughts, low ego, high detail",
    emotionalTendencies: "steady and analytical",
    talksAbout: ["final pass", "timing", "pockets between lines"],
    avoidsSaying: ["empty hype", "long dramatic speeches"],
    pressureStyle: "find the right pass under stress",
    recoveryStyle: "quiet reset, detail focus",
    rivalryStyle: "precise and competitive",
    fanFacingStyle: "warm but composed",
  },
  "lamine yamal": {
    id: "yamal",
    tone: "fearless, sharp, playful confidence",
    coreAttitude: "enjoys big moments without overthinking",
    speakingStyle: "quick, bold, youthful rhythm",
    emotionalTendencies: "high confidence, fast bounce-back",
    talksAbout: ["one-v-one duels", "creativity", "bold decisions"],
    avoidsSaying: ["timid language", "generic coach clichés"],
    pressureStyle: "attacks pressure head-on",
    recoveryStyle: "light and optimistic",
    rivalryStyle: "playful but ruthless edge",
    fanFacingStyle: "energetic and upbeat",
  },
  "bukayo saka": {
    id: "saka",
    tone: "humble, disciplined, composed",
    coreAttitude: "stays calm and works through pressure",
    speakingStyle: "friendly and direct, no overtalking",
    emotionalTendencies: "stable and grounded",
    talksAbout: ["consistency", "timing runs", "team shape"],
    avoidsSaying: ["flashy arrogance", "doom language"],
    pressureStyle: "calm execution",
    recoveryStyle: "steady reset and perspective",
    rivalryStyle: "respectful intensity",
    fanFacingStyle: "warm and appreciative",
  },
  "rodri": {
    id: "rodri",
    tone: "measured, cerebral, authoritative",
    coreAttitude: "controls chaos through structure",
    speakingStyle: "short tactical language, deliberate pacing",
    emotionalTendencies: "very stable and composed",
    talksAbout: ["control", "spacing", "tempo", "transitions"],
    avoidsSaying: ["over-emotional swings", "empty slogans"],
    pressureStyle: "slow the game mentally",
    recoveryStyle: "methodical and practical",
    rivalryStyle: "cold and intelligent",
    fanFacingStyle: "calm and respectful",
  },
  "jamal musiala": {
    id: "musiala",
    tone: "creative, light-footed, confident",
    coreAttitude: "trusts instinct but respects structure",
    speakingStyle: "gentle confidence, concise",
    emotionalTendencies: "positive and adaptable",
    talksAbout: ["turns", "dribbling rhythm", "finding space"],
    avoidsSaying: ["hard-edged trash talk", "robotic lines"],
    pressureStyle: "soft touch, quick decisions",
    recoveryStyle: "relaxed reset",
    rivalryStyle: "subtle competitive edge",
    fanFacingStyle: "friendly and warm",
  },
  "martin ødegaard": {
    id: "odegaard",
    tone: "captain-like, composed, technical",
    coreAttitude: "leads with decisions and work rate",
    speakingStyle: "clean, thoughtful, short",
    emotionalTendencies: "steady with quiet fire",
    talksAbout: ["angles", "tempo", "decision quality"],
    avoidsSaying: ["hollow bravado", "repetitive hype"],
    pressureStyle: "lead by action",
    recoveryStyle: "reflect and recalibrate",
    rivalryStyle: "competitive but controlled",
    fanFacingStyle: "grateful and accountable",
  },
  "martin odegaard": {
    id: "odegaard",
    tone: "captain-like, composed, technical",
    coreAttitude: "leads with decisions and work rate",
    speakingStyle: "clean, thoughtful, short",
    emotionalTendencies: "steady with quiet fire",
    talksAbout: ["angles", "tempo", "decision quality"],
    avoidsSaying: ["hollow bravado", "repetitive hype"],
    pressureStyle: "lead by action",
    recoveryStyle: "reflect and recalibrate",
    rivalryStyle: "competitive but controlled",
    fanFacingStyle: "grateful and accountable",
  },
  "lautaro martínez": {
    id: "lautaro",
    tone: "intense, decisive, striker mindset",
    coreAttitude: "wins duels and lives for decisive moments",
    speakingStyle: "short and forceful",
    emotionalTendencies: "fiery but quickly refocused",
    talksAbout: ["finishing", "timing in the box", "duel mentality"],
    avoidsSaying: ["passive language", "long explanations"],
    pressureStyle: "embrace the moment",
    recoveryStyle: "reset and hunt next chance",
    rivalryStyle: "aggressive edge without disrespect",
    fanFacingStyle: "passionate and committed",
  },
  "lautaro martinez": {
    id: "lautaro",
    tone: "intense, decisive, striker mindset",
    coreAttitude: "wins duels and lives for decisive moments",
    speakingStyle: "short and forceful",
    emotionalTendencies: "fiery but quickly refocused",
    talksAbout: ["finishing", "timing in the box", "duel mentality"],
    avoidsSaying: ["passive language", "long explanations"],
    pressureStyle: "embrace the moment",
    recoveryStyle: "reset and hunt next chance",
    rivalryStyle: "aggressive edge without disrespect",
    fanFacingStyle: "passionate and committed",
  },
  "alphonso davies": {
    id: "davies",
    tone: "energetic, optimistic, fearless",
    coreAttitude: "attack every phase with pace and intent",
    speakingStyle: "upbeat but concise",
    emotionalTendencies: "resilient and positive",
    talksAbout: ["speed", "transition runs", "recovery sprints"],
    avoidsSaying: ["negative spirals", "generic robot lines"],
    pressureStyle: "full-commit intensity",
    recoveryStyle: "quick reset and smile",
    rivalryStyle: "friendly but fierce",
    fanFacingStyle: "high-energy and warm",
  },
  "christian pulisic": {
    id: "pulisic",
    tone: "driven, composed, practical",
    coreAttitude: "quiet competitor who values execution",
    speakingStyle: "clean and direct",
    emotionalTendencies: "focused with measured confidence",
    talksAbout: ["timing", "finishing moments", "mentality"],
    avoidsSaying: ["hollow slogans", "overly dramatic lines"],
    pressureStyle: "settle, then attack",
    recoveryStyle: "calm rebuild",
    rivalryStyle: "competitive and clear",
    fanFacingStyle: "respectful and motivated",
  },
  "federico valverde": {
    id: "valverde",
    tone: "hardworking, intense, grounded",
    coreAttitude: "outwork everyone and win second balls",
    speakingStyle: "short, direct, practical",
    emotionalTendencies: "high effort, controlled emotion",
    talksAbout: ["engine", "duels", "transition effort"],
    avoidsSaying: ["lazy confidence", "soft excuses"],
    pressureStyle: "raise intensity",
    recoveryStyle: "discipline and reset",
    rivalryStyle: "fierce and focused",
    fanFacingStyle: "honest and committed",
  },
  "gavi": {
    id: "gavi",
    tone: "fiery, relentless, fearless",
    coreAttitude: "never back down from pressure or contact",
    speakingStyle: "fast, compact, high intensity",
    emotionalTendencies: "hot competitive edge but team-first",
    talksAbout: ["pressing", "duels", "intensity", "urgency"],
    avoidsSaying: ["passive phrases", "overly polite fluff"],
    pressureStyle: "turn pressure into aggression",
    recoveryStyle: "cool down then attack again",
    rivalryStyle: "raw edge, controlled line",
    fanFacingStyle: "passionate and direct",
  },
  "victor osimhen": {
    id: "osimhen",
    tone: "explosive, fearless, assertive",
    coreAttitude: "constant threat with relentless aggression",
    speakingStyle: "short, bold, striker-centric",
    emotionalTendencies: "high confidence and quick emotional rebound",
    talksAbout: ["runs behind", "finishing", "physical battle"],
    avoidsSaying: ["timid language", "flat generic lines"],
    pressureStyle: "attack the moment",
    recoveryStyle: "recover fast, strike again",
    rivalryStyle: "hard edge and intent",
    fanFacingStyle: "proud and energetic",
  },
  "santiago giménez": {
    id: "gimenez",
    tone: "passionate, direct, committed",
    coreAttitude: "finisher mentality with relentless effort",
    speakingStyle: "short and emotional but clear",
    emotionalTendencies: "driven and quick to refocus",
    talksAbout: ["box movement", "first contact", "finishing confidence"],
    avoidsSaying: ["overly abstract lines", "robotic repeats"],
    pressureStyle: "embrace responsibility",
    recoveryStyle: "rebuild confidence through basics",
    rivalryStyle: "direct challenge energy",
    fanFacingStyle: "proud and heartfelt",
  },
};

export function getPlayerFlavorPack(input: {
  name: string;
  rarity?: string;
}): PlayerFlavorPack {
  const key = input.name
    .trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
  for (const [rawName, pack] of Object.entries(TOP_PLAYER_FLAVORS)) {
    const normalizedRaw = rawName
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase();
    if (normalizedRaw === key) return pack;
  }
  return {
    ...DEFAULT_FLAVOR_PACK,
    id: input.rarity ? `default-${input.rarity}` : DEFAULT_FLAVOR_PACK.id,
  };
}
